### ISSUE TITLE
Are the `react-hmre` preset and react-hot-loader redundant?

### ISSUE THREAD

**Issue by aaronjensen** [philholden/react-project-archetype#1]
I believe they are alternatives, it seems like including both is unnecessary. For my own project I've stuck to `react-hmre` so redbox works.

Either way, thanks for the template, I wish I would have found it before we rolled nearly the same stack :/

**Comment by philholden** [comment]
Thanks removed it.

Also updated Webpack 2 .babelrc settings to fix the recent break. You will probably need to delete `node_modules` and `npm install` if applying these changes.

**Comment by aaronjensen** [comment]
👍  btw, it looks like you may not have pushed the changes.
